[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "soup-tutorial"
authors = [{name = "Graziella", email = "h42318@gmail.com"}]
dynamic = ["version", "description"]
